export const LOAD_PHOTOS = 'LOAD_PHOTOS';
export const LOAD_PHOTOS_SUCCESS = 'LOAD_PHOTOS_SUCCESS';
export const GET_FULL_SIZE_PHOTO = 'GET_FULL_SIZE_PHOTO';
export const GET_FULL_SIZE_PHOTO_SUCCESS = 'GET_FULL_SIZE_PHOTO_SUCCESS';
export const REMOVE_PHOTOS = 'REMOVE_PHOTOS';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
